/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalkIndexRouteImport } from './routes/walk.index'
import { Route as WalkStartRouteImport } from './routes/walk.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkIndexRoute = WalkIndexRouteImport.update({
  id: '/walk/',
  path: '/walk/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkStartRoute = WalkStartRouteImport.update({
  id: '/walk/start',
  path: '/walk/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/walk/start': typeof WalkStartRoute
  '/walk/': typeof WalkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/walk/start': typeof WalkStartRoute
  '/walk': typeof WalkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/walk/start': typeof WalkStartRoute
  '/walk/': typeof WalkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/walk/start' | '/walk/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/walk/start' | '/walk'
  id: '__root__' | '/' | '/walk/start' | '/walk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WalkStartRoute: typeof WalkStartRoute
  WalkIndexRoute: typeof WalkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/': {
      id: '/walk/'
      path: '/walk'
      fullPath: '/walk/'
      preLoaderRoute: typeof WalkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/start': {
      id: '/walk/start'
      path: '/walk/start'
      fullPath: '/walk/start'
      preLoaderRoute: typeof WalkStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WalkStartRoute: WalkStartRoute,
  WalkIndexRoute: WalkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
