/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportHazardRouteImport } from './routes/report-hazard'
import { Route as OnetouchRouteImport } from './routes/onetouch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalkIndexRouteImport } from './routes/walk.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WalkStartRouteImport } from './routes/walk.start'
import { Route as AuthPendingRouteImport } from './routes/auth.pending'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AdminMilestonesRouteImport } from './routes/admin.milestones'
import { Route as AdminHazardsRouteImport } from './routes/admin.hazards'
import { Route as AdminFieldSurveyRouteImport } from './routes/admin.field-survey'
import { Route as AdminFieldModeRouteImport } from './routes/admin.field-mode'
import { Route as AdminEntrancesRouteImport } from './routes/admin.entrances'
import { Route as AdminDataStatusRouteImport } from './routes/admin.data-status'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportHazardRoute = ReportHazardRouteImport.update({
  id: '/report-hazard',
  path: '/report-hazard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnetouchRoute = OnetouchRouteImport.update({
  id: '/onetouch',
  path: '/onetouch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkIndexRoute = WalkIndexRouteImport.update({
  id: '/walk/',
  path: '/walk/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkStartRoute = WalkStartRouteImport.update({
  id: '/walk/start',
  path: '/walk/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingRoute = AuthPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMilestonesRoute = AdminMilestonesRouteImport.update({
  id: '/admin/milestones',
  path: '/admin/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHazardsRoute = AdminHazardsRouteImport.update({
  id: '/admin/hazards',
  path: '/admin/hazards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldSurveyRoute = AdminFieldSurveyRouteImport.update({
  id: '/admin/field-survey',
  path: '/admin/field-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldModeRoute = AdminFieldModeRouteImport.update({
  id: '/admin/field-mode',
  path: '/admin/field-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntrancesRoute = AdminEntrancesRouteImport.update({
  id: '/admin/entrances',
  path: '/admin/entrances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataStatusRoute = AdminDataStatusRouteImport.update({
  id: '/admin/data-status',
  path: '/admin/data-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onetouch': typeof OnetouchRoute
  '/report-hazard': typeof ReportHazardRoute
  '/settings': typeof SettingsRoute
  '/admin/data-status': typeof AdminDataStatusRoute
  '/admin/entrances': typeof AdminEntrancesRoute
  '/admin/field-mode': typeof AdminFieldModeRoute
  '/admin/field-survey': typeof AdminFieldSurveyRoute
  '/admin/hazards': typeof AdminHazardsRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/pending': typeof AuthPendingRoute
  '/walk/start': typeof WalkStartRoute
  '/admin/': typeof AdminIndexRoute
  '/walk/': typeof WalkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onetouch': typeof OnetouchRoute
  '/report-hazard': typeof ReportHazardRoute
  '/settings': typeof SettingsRoute
  '/admin/data-status': typeof AdminDataStatusRoute
  '/admin/entrances': typeof AdminEntrancesRoute
  '/admin/field-mode': typeof AdminFieldModeRoute
  '/admin/field-survey': typeof AdminFieldSurveyRoute
  '/admin/hazards': typeof AdminHazardsRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/pending': typeof AuthPendingRoute
  '/walk/start': typeof WalkStartRoute
  '/admin': typeof AdminIndexRoute
  '/walk': typeof WalkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onetouch': typeof OnetouchRoute
  '/report-hazard': typeof ReportHazardRoute
  '/settings': typeof SettingsRoute
  '/admin/data-status': typeof AdminDataStatusRoute
  '/admin/entrances': typeof AdminEntrancesRoute
  '/admin/field-mode': typeof AdminFieldModeRoute
  '/admin/field-survey': typeof AdminFieldSurveyRoute
  '/admin/hazards': typeof AdminHazardsRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/pending': typeof AuthPendingRoute
  '/walk/start': typeof WalkStartRoute
  '/admin/': typeof AdminIndexRoute
  '/walk/': typeof WalkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onetouch'
    | '/report-hazard'
    | '/settings'
    | '/admin/data-status'
    | '/admin/entrances'
    | '/admin/field-mode'
    | '/admin/field-survey'
    | '/admin/hazards'
    | '/admin/milestones'
    | '/api/tts'
    | '/auth/pending'
    | '/walk/start'
    | '/admin/'
    | '/walk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onetouch'
    | '/report-hazard'
    | '/settings'
    | '/admin/data-status'
    | '/admin/entrances'
    | '/admin/field-mode'
    | '/admin/field-survey'
    | '/admin/hazards'
    | '/admin/milestones'
    | '/api/tts'
    | '/auth/pending'
    | '/walk/start'
    | '/admin'
    | '/walk'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onetouch'
    | '/report-hazard'
    | '/settings'
    | '/admin/data-status'
    | '/admin/entrances'
    | '/admin/field-mode'
    | '/admin/field-survey'
    | '/admin/hazards'
    | '/admin/milestones'
    | '/api/tts'
    | '/auth/pending'
    | '/walk/start'
    | '/admin/'
    | '/walk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OnetouchRoute: typeof OnetouchRoute
  ReportHazardRoute: typeof ReportHazardRoute
  SettingsRoute: typeof SettingsRoute
  AdminDataStatusRoute: typeof AdminDataStatusRoute
  AdminEntrancesRoute: typeof AdminEntrancesRoute
  AdminFieldModeRoute: typeof AdminFieldModeRoute
  AdminFieldSurveyRoute: typeof AdminFieldSurveyRoute
  AdminHazardsRoute: typeof AdminHazardsRoute
  AdminMilestonesRoute: typeof AdminMilestonesRoute
  ApiTtsRoute: typeof ApiTtsRoute
  WalkStartRoute: typeof WalkStartRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WalkIndexRoute: typeof WalkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-hazard': {
      id: '/report-hazard'
      path: '/report-hazard'
      fullPath: '/report-hazard'
      preLoaderRoute: typeof ReportHazardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onetouch': {
      id: '/onetouch'
      path: '/onetouch'
      fullPath: '/onetouch'
      preLoaderRoute: typeof OnetouchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/': {
      id: '/walk/'
      path: '/walk'
      fullPath: '/walk/'
      preLoaderRoute: typeof WalkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/start': {
      id: '/walk/start'
      path: '/walk/start'
      fullPath: '/walk/start'
      preLoaderRoute: typeof WalkStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending': {
      id: '/auth/pending'
      path: '/pending'
      fullPath: '/auth/pending'
      preLoaderRoute: typeof AuthPendingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/milestones': {
      id: '/admin/milestones'
      path: '/admin/milestones'
      fullPath: '/admin/milestones'
      preLoaderRoute: typeof AdminMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hazards': {
      id: '/admin/hazards'
      path: '/admin/hazards'
      fullPath: '/admin/hazards'
      preLoaderRoute: typeof AdminHazardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/field-survey': {
      id: '/admin/field-survey'
      path: '/admin/field-survey'
      fullPath: '/admin/field-survey'
      preLoaderRoute: typeof AdminFieldSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/field-mode': {
      id: '/admin/field-mode'
      path: '/admin/field-mode'
      fullPath: '/admin/field-mode'
      preLoaderRoute: typeof AdminFieldModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entrances': {
      id: '/admin/entrances'
      path: '/admin/entrances'
      fullPath: '/admin/entrances'
      preLoaderRoute: typeof AdminEntrancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-status': {
      id: '/admin/data-status'
      path: '/admin/data-status'
      fullPath: '/admin/data-status'
      preLoaderRoute: typeof AdminDataStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthPendingRoute: typeof AuthPendingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPendingRoute: AuthPendingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OnetouchRoute: OnetouchRoute,
  ReportHazardRoute: ReportHazardRoute,
  SettingsRoute: SettingsRoute,
  AdminDataStatusRoute: AdminDataStatusRoute,
  AdminEntrancesRoute: AdminEntrancesRoute,
  AdminFieldModeRoute: AdminFieldModeRoute,
  AdminFieldSurveyRoute: AdminFieldSurveyRoute,
  AdminHazardsRoute: AdminHazardsRoute,
  AdminMilestonesRoute: AdminMilestonesRoute,
  ApiTtsRoute: ApiTtsRoute,
  WalkStartRoute: WalkStartRoute,
  AdminIndexRoute: AdminIndexRoute,
  WalkIndexRoute: WalkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
